/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // BORO AI palette — extracted from design tokens
        background: '#131313',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-tint': '#abd600',
        primary: '#ffffff',
        'on-primary': '#283500',
        'primary-container': '#c3f400',
        'on-primary-container': '#556d00',
        'primary-fixed': '#c3f400',
        'primary-fixed-dim': '#abd600',
        'on-primary-fixed': '#161e00',
        'on-primary-fixed-variant': '#3c4d00',
        'inverse-primary': '#506600',
        secondary: '#b3c5ff',
        'on-secondary': '#002b75',
        'secondary-container': '#0266ff',
        'on-secondary-container': '#f9f7ff',
        'secondary-fixed': '#dae1ff',
        'secondary-fixed-dim': '#b3c5ff',
        'on-secondary-fixed': '#001849',
        'on-secondary-fixed-variant': '#003fa4',
        tertiary: '#ffffff',
        'on-tertiary': '#313030',
        'tertiary-container': '#e5e2e1',
        'on-tertiary-container': '#656464',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474746',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c9ac',
        outline: '#8e9379',
        'outline-variant': '#444933',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        // Probability tier colors
        'prob-high': '#22C55E',
        'prob-mid': '#EAB308',
        'prob-low': '#EF4444',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'cp-mobile': '16px',
        'sg-md': '16px',
        'sg-sm': '8px',
        'sg-lg': '24px',
        gutter: '16px',
      },
      fontFamily: {
        display: ['HankenGrotesk_800ExtraBold'],
        headline: ['HankenGrotesk_700Bold'],
        'headline-md': ['HankenGrotesk_600SemiBold'],
        stats: ['HankenGrotesk_700Bold'],
        body: ['Inter_400Regular'],
        'body-bold': ['Inter_600SemiBold'],
        label: ['Inter_600SemiBold'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.96px', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.32px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.6px', fontWeight: '600' }],
        'stats-num': ['20px', { lineHeight: '24px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
