/**
 * Leagues tracked by BORO AI.
 *
 * Generated automatically from active plan subscriptions.
 */
export interface TrackedLeague {
  id: number;
  sportmonksId: number;
  name: string;
  shortName: string;
  country: string;
  countryCode?: string;
  emoji: string;
  isInternational?: boolean;
  isCup?: boolean;
}

export const FOOTBALL_LEAGUES: TrackedLeague[] = [
  {
    "id": 2,
    "sportmonksId": 2,
    "name": "Champions League",
    "shortName": "Champions Leagu",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 5,
    "sportmonksId": 5,
    "name": "Europa League",
    "shortName": "Europa League",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 9,
    "sportmonksId": 9,
    "name": "Championship",
    "shortName": "Championship",
    "country": "England",
    "countryCode": "GB",
    "emoji": "🇬🇧",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 32,
    "sportmonksId": 32,
    "name": "Premier League Cup",
    "shortName": "Premier League ",
    "country": "England",
    "countryCode": "GB",
    "emoji": "🇬🇧",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 44,
    "sportmonksId": 44,
    "name": "WSL 2",
    "shortName": "WSL 2",
    "country": "England",
    "countryCode": "GB",
    "emoji": "🇬🇧",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 77,
    "sportmonksId": 77,
    "name": "Tweede Divisie",
    "shortName": "Tweede Divisie",
    "country": "Netherlands",
    "countryCode": "NL",
    "emoji": "🇳🇱",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 81,
    "sportmonksId": 81,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "Netherlands",
    "countryCode": "NL",
    "emoji": "🇳🇱",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 169,
    "sportmonksId": 169,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "Germany",
    "countryCode": "DE",
    "emoji": "🇩🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 172,
    "sportmonksId": 172,
    "name": "Superliga",
    "shortName": "Superliga",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 175,
    "sportmonksId": 175,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 181,
    "sportmonksId": 181,
    "name": "Admiral Bundesliga",
    "shortName": "Admiral Bundesl",
    "country": "Austria",
    "countryCode": "AT",
    "emoji": "🇦🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 184,
    "sportmonksId": 184,
    "name": "2. Liga",
    "shortName": "2. Liga",
    "country": "Austria",
    "countryCode": "AT",
    "emoji": "🇦🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 190,
    "sportmonksId": 190,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 199,
    "sportmonksId": 199,
    "name": "Vysshaya Liga",
    "shortName": "Vysshaya Liga",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 220,
    "sportmonksId": 220,
    "name": "Premier Liga",
    "shortName": "Premier Liga",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 229,
    "sportmonksId": 229,
    "name": "First League",
    "shortName": "First League",
    "country": "Bulgaria",
    "countryCode": "BG",
    "emoji": "🇧🇬",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 244,
    "sportmonksId": 244,
    "name": "1. HNL",
    "shortName": "1. HNL",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 247,
    "sportmonksId": 247,
    "name": "2. HNL",
    "shortName": "2. HNL",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 253,
    "sportmonksId": 253,
    "name": "1. Division",
    "shortName": "1. Division",
    "country": "Cyprus",
    "countryCode": "CY",
    "emoji": "🇨🇾",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 262,
    "sportmonksId": 262,
    "name": "Chance Liga",
    "shortName": "Chance Liga",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 265,
    "sportmonksId": 265,
    "name": "Chance Národní Liga",
    "shortName": "Chance Národní ",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 274,
    "sportmonksId": 274,
    "name": "First Division",
    "shortName": "First Division",
    "country": "Denmark",
    "countryCode": "DK",
    "emoji": "🇩🇰",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 286,
    "sportmonksId": 286,
    "name": "Meistriliiga",
    "shortName": "Meistriliiga",
    "country": "Estonia",
    "countryCode": "EE",
    "emoji": "🇪🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 289,
    "sportmonksId": 289,
    "name": "Esiliiga A",
    "shortName": "Esiliiga A",
    "country": "Estonia",
    "countryCode": "EE",
    "emoji": "🇪🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 292,
    "sportmonksId": 292,
    "name": "Veikkausliiga",
    "shortName": "Veikkausliiga",
    "country": "Finland",
    "countryCode": "FI",
    "emoji": "🇫🇮",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 295,
    "sportmonksId": 295,
    "name": "Ykkösliiga",
    "shortName": "Ykkösliiga",
    "country": "Finland",
    "countryCode": "FI",
    "emoji": "🇫🇮",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 319,
    "sportmonksId": 319,
    "name": "Crystalbet Erovnuli Liga",
    "shortName": "Crystalbet Erov",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 325,
    "sportmonksId": 325,
    "name": "Super League",
    "shortName": "Super League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 334,
    "sportmonksId": 334,
    "name": "NB I",
    "shortName": "NB I",
    "country": "Hungary",
    "countryCode": "HU",
    "emoji": "🇭🇺",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 345,
    "sportmonksId": 345,
    "name": "Besta deild",
    "shortName": "Besta deild",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 360,
    "sportmonksId": 360,
    "name": "Premier Division",
    "shortName": "Premier Divisio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 363,
    "sportmonksId": 363,
    "name": "First Division",
    "shortName": "First Division",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 372,
    "sportmonksId": 372,
    "name": "Ligat ha\\'Al",
    "shortName": "Ligat ha\\'Al",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 375,
    "sportmonksId": 375,
    "name": "Liga Leumit",
    "shortName": "Liga Leumit",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 390,
    "sportmonksId": 390,
    "name": "Coppa Italia",
    "shortName": "Coppa Italia",
    "country": "Italy",
    "countryCode": "IT",
    "emoji": "🇮🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 393,
    "sportmonksId": 393,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 399,
    "sportmonksId": 399,
    "name": "Virsliga",
    "shortName": "Virsliga",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 405,
    "sportmonksId": 405,
    "name": "A Lyga",
    "shortName": "A Lyga",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 420,
    "sportmonksId": 420,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "Malta",
    "countryCode": "MT",
    "emoji": "🇲🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 432,
    "sportmonksId": 432,
    "name": "First League",
    "shortName": "First League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 438,
    "sportmonksId": 438,
    "name": "Premiership",
    "shortName": "Premiership",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 444,
    "sportmonksId": 444,
    "name": "Eliteserien",
    "shortName": "Eliteserien",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 447,
    "sportmonksId": 447,
    "name": "1. Division",
    "shortName": "1. Division",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 474,
    "sportmonksId": 474,
    "name": "Superliga",
    "shortName": "Superliga",
    "country": "Romania",
    "countryCode": "RO",
    "emoji": "🇷🇴",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 486,
    "sportmonksId": 486,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 489,
    "sportmonksId": 489,
    "name": "FNL",
    "shortName": "FNL",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 498,
    "sportmonksId": 498,
    "name": "Youth League",
    "shortName": "Youth League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 501,
    "sportmonksId": 501,
    "name": "Premiership",
    "shortName": "Premiership",
    "country": "Scotland",
    "countryCode": "SCO",
    "emoji": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 531,
    "sportmonksId": 531,
    "name": "Super Liga",
    "shortName": "Super Liga",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 534,
    "sportmonksId": 534,
    "name": "Prva Liga",
    "shortName": "Prva Liga",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 540,
    "sportmonksId": 540,
    "name": "Niké Liga",
    "shortName": "Niké Liga",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 555,
    "sportmonksId": 555,
    "name": "1. SNL",
    "shortName": "1. SNL",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 573,
    "sportmonksId": 573,
    "name": "Allsvenskan",
    "shortName": "Allsvenskan",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 576,
    "sportmonksId": 576,
    "name": "Damallsvenskan",
    "shortName": "Damallsvenskan",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 579,
    "sportmonksId": 579,
    "name": "Superettan",
    "shortName": "Superettan",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 585,
    "sportmonksId": 585,
    "name": "Ettan: North",
    "shortName": "Ettan: North",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 588,
    "sportmonksId": 588,
    "name": "Ettan: South",
    "shortName": "Ettan: South",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 609,
    "sportmonksId": 609,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 624,
    "sportmonksId": 624,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 636,
    "sportmonksId": 636,
    "name": "Liga Profesional de Fútbol",
    "shortName": "Liga Profesiona",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 639,
    "sportmonksId": 639,
    "name": "Torneo Federal B - Pampeana Norte",
    "shortName": "Torneo Federal ",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 642,
    "sportmonksId": 642,
    "name": "Copa Argentina",
    "shortName": "Copa Argentina",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 645,
    "sportmonksId": 645,
    "name": "Primera B Nacional",
    "shortName": "Primera B Nacio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 648,
    "sportmonksId": 648,
    "name": "Serie A",
    "shortName": "Serie A",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 651,
    "sportmonksId": 651,
    "name": "Serie B",
    "shortName": "Serie B",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 654,
    "sportmonksId": 654,
    "name": "Copa do Brasil",
    "shortName": "Copa do Brasil",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 657,
    "sportmonksId": 657,
    "name": "Serie C",
    "shortName": "Serie C",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 660,
    "sportmonksId": 660,
    "name": "Serie D",
    "shortName": "Serie D",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 663,
    "sportmonksId": 663,
    "name": "Primera Division",
    "shortName": "Primera Divisio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 666,
    "sportmonksId": 666,
    "name": "Primera B",
    "shortName": "Primera B",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 672,
    "sportmonksId": 672,
    "name": "Liga BetPlay",
    "shortName": "Liga BetPlay",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 678,
    "sportmonksId": 678,
    "name": "Primera B",
    "shortName": "Primera B",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 687,
    "sportmonksId": 687,
    "name": "Primera Division",
    "shortName": "Primera Divisio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 696,
    "sportmonksId": 696,
    "name": "Liga Pro",
    "shortName": "Liga Pro",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 699,
    "sportmonksId": 699,
    "name": "Liga Pro Serie B",
    "shortName": "Liga Pro Serie ",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 711,
    "sportmonksId": 711,
    "name": "CAF World Cup Qualifiers",
    "shortName": "CAF World Cup Q",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 714,
    "sportmonksId": 714,
    "name": "WC Qualification Asia",
    "shortName": "WC Qualificatio",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 717,
    "sportmonksId": 717,
    "name": "WC Qualification Concacaf",
    "shortName": "WC Qualificatio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 720,
    "sportmonksId": 720,
    "name": "WC Qualification Europe",
    "shortName": "WC Qualificatio",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 723,
    "sportmonksId": 723,
    "name": "WC Qualification Oceania",
    "shortName": "WC Qualificatio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 726,
    "sportmonksId": 726,
    "name": "WC Qualification South America",
    "shortName": "WC Qualificatio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 729,
    "sportmonksId": 729,
    "name": "WC Qualification Intercontinental Playoffs",
    "shortName": "WC Qualificatio",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 732,
    "sportmonksId": 732,
    "name": "World Cup",
    "shortName": "World Cup",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 743,
    "sportmonksId": 743,
    "name": "Liga MX",
    "shortName": "Liga MX",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 746,
    "sportmonksId": 746,
    "name": "Copa MX",
    "shortName": "Copa MX",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 749,
    "sportmonksId": 749,
    "name": "Liga de Expansión MX",
    "shortName": "Liga de Expansi",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 755,
    "sportmonksId": 755,
    "name": "Division 1",
    "shortName": "Division 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 761,
    "sportmonksId": 761,
    "name": "Division Intermedia",
    "shortName": "Division Interm",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 764,
    "sportmonksId": 764,
    "name": "Primera Division",
    "shortName": "Primera Divisio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 767,
    "sportmonksId": 767,
    "name": "Segunda Division",
    "shortName": "Segunda Divisio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 770,
    "sportmonksId": 770,
    "name": "Primera Division",
    "shortName": "Primera Divisio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 779,
    "sportmonksId": 779,
    "name": "Major League Soccer",
    "shortName": "Major League So",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 782,
    "sportmonksId": 782,
    "name": "US Open Cup",
    "shortName": "US Open Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 788,
    "sportmonksId": 788,
    "name": "NASL",
    "shortName": "NASL",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 791,
    "sportmonksId": 791,
    "name": "USL Championship",
    "shortName": "USL Championshi",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 797,
    "sportmonksId": 797,
    "name": "USL League Two",
    "shortName": "USL League Two",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 800,
    "sportmonksId": 800,
    "name": "Primera Division",
    "shortName": "Primera Divisio",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 806,
    "sportmonksId": 806,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "South Africa",
    "countryCode": "ZA",
    "emoji": "🇿🇦",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 809,
    "sportmonksId": 809,
    "name": "Ligue 1",
    "shortName": "Ligue 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 824,
    "sportmonksId": 824,
    "name": "Super Ligue",
    "shortName": "Super Ligue",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 827,
    "sportmonksId": 827,
    "name": "Ligue 1",
    "shortName": "Ligue 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 830,
    "sportmonksId": 830,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 851,
    "sportmonksId": 851,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 860,
    "sportmonksId": 860,
    "name": "Botola Pro",
    "shortName": "Botola Pro",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 887,
    "sportmonksId": 887,
    "name": "Premier Soccer League",
    "shortName": "Premier Soccer ",
    "country": "Zimbabwe",
    "countryCode": "ZW",
    "emoji": "🇿🇼",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 902,
    "sportmonksId": 902,
    "name": "Persian Gulf Pro League",
    "shortName": "Persian Gulf Pr",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 911,
    "sportmonksId": 911,
    "name": "Iraqi League",
    "shortName": "Iraqi League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 920,
    "sportmonksId": 920,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 923,
    "sportmonksId": 923,
    "name": "Zain Premier League",
    "shortName": "Zain Premier Le",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 935,
    "sportmonksId": 935,
    "name": "Professional League",
    "shortName": "Professional Le",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 938,
    "sportmonksId": 938,
    "name": "Stars League",
    "shortName": "Stars League",
    "country": "Qatar",
    "countryCode": "QA",
    "emoji": "🇶🇦",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 944,
    "sportmonksId": 944,
    "name": "Pro League",
    "shortName": "Pro League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 947,
    "sportmonksId": 947,
    "name": "Division 1",
    "shortName": "Division 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 956,
    "sportmonksId": 956,
    "name": "Ligue 1",
    "shortName": "Ligue 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 959,
    "sportmonksId": 959,
    "name": "UAE Pro League",
    "shortName": "UAE Pro League",
    "country": "UAE",
    "countryCode": "AE",
    "emoji": "🇦🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 968,
    "sportmonksId": 968,
    "name": "J1 League",
    "shortName": "J1 League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 971,
    "sportmonksId": 971,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 983,
    "sportmonksId": 983,
    "name": "Canadian Soccer League",
    "shortName": "Canadian Soccer",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 989,
    "sportmonksId": 989,
    "name": "Super League",
    "shortName": "Super League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 992,
    "sportmonksId": 992,
    "name": "League One",
    "shortName": "League One",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1007,
    "sportmonksId": 1007,
    "name": "Indian Super League",
    "shortName": "Indian Super Le",
    "country": "India",
    "countryCode": "IN",
    "emoji": "🇮🇳",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1016,
    "sportmonksId": 1016,
    "name": "Indonesia Championship",
    "shortName": "Indonesia Champ",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1019,
    "sportmonksId": 1019,
    "name": "Liga 1",
    "shortName": "Liga 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1022,
    "sportmonksId": 1022,
    "name": "J2-League",
    "shortName": "J2-League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1025,
    "sportmonksId": 1025,
    "name": "J3-League",
    "shortName": "J3-League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1028,
    "sportmonksId": 1028,
    "name": "Emperor Cup",
    "shortName": "Emperor Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1031,
    "sportmonksId": 1031,
    "name": "J-League Cup",
    "shortName": "J-League Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1034,
    "sportmonksId": 1034,
    "name": "K League 1",
    "shortName": "K League 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1037,
    "sportmonksId": 1037,
    "name": "K3 League",
    "shortName": "K3 League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1040,
    "sportmonksId": 1040,
    "name": "K4 League",
    "shortName": "K4 League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1049,
    "sportmonksId": 1049,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1064,
    "sportmonksId": 1064,
    "name": "Thai Premier League",
    "shortName": "Thai Premier Le",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1067,
    "sportmonksId": 1067,
    "name": "Thai League Two",
    "shortName": "Thai League Two",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1073,
    "sportmonksId": 1073,
    "name": "V-League",
    "shortName": "V-League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1076,
    "sportmonksId": 1076,
    "name": "V-League 2",
    "shortName": "V-League 2",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1079,
    "sportmonksId": 1079,
    "name": "Vietnamese Cup",
    "shortName": "Vietnamese Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1082,
    "sportmonksId": 1082,
    "name": "Friendly International",
    "shortName": "Friendly Intern",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1093,
    "sportmonksId": 1093,
    "name": "Primera C",
    "shortName": "Primera C",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1098,
    "sportmonksId": 1098,
    "name": "Liga De Futbol Prof",
    "shortName": "Liga De Futbol ",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1101,
    "sportmonksId": 1101,
    "name": "Club Friendlies 1",
    "shortName": "Club Friendlies",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1103,
    "sportmonksId": 1103,
    "name": "African Nations Championship",
    "shortName": "African Nations",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1104,
    "sportmonksId": 1104,
    "name": "ASEAN Championship",
    "shortName": "ASEAN Champions",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1105,
    "sportmonksId": 1105,
    "name": "AFC Asian Cup",
    "shortName": "AFC Asian Cup",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1106,
    "sportmonksId": 1106,
    "name": "Asian Cup Qualification",
    "shortName": "Asian Cup Quali",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1108,
    "sportmonksId": 1108,
    "name": "CAF Confederations Cup",
    "shortName": "CAF Confederati",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1112,
    "sportmonksId": 1112,
    "name": "CONCACAF Gold Cup",
    "shortName": "CONCACAF Gold C",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1114,
    "sportmonksId": 1114,
    "name": "Copa America",
    "shortName": "Copa America",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1116,
    "sportmonksId": 1116,
    "name": "Copa Sudamericana",
    "shortName": "Copa Sudamerica",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1117,
    "sportmonksId": 1117,
    "name": "Africa Cup of Nations",
    "shortName": "Africa Cup of N",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1118,
    "sportmonksId": 1118,
    "name": "Africa Cup of Nations Qualifications",
    "shortName": "Africa Cup of N",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1119,
    "sportmonksId": 1119,
    "name": "EAFF E-1 Football Championship",
    "shortName": "EAFF E-1 Footba",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1122,
    "sportmonksId": 1122,
    "name": "Copa Libertadores",
    "shortName": "Copa Libertador",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1124,
    "sportmonksId": 1124,
    "name": "OFC Nations Cup",
    "shortName": "OFC Nations Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1125,
    "sportmonksId": 1125,
    "name": "Olympic Games",
    "shortName": "Olympic Games",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1126,
    "sportmonksId": 1126,
    "name": "Olympic Games Women",
    "shortName": "Olympic Games W",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1127,
    "sportmonksId": 1127,
    "name": "SAFF Championship",
    "shortName": "SAFF Championsh",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1158,
    "sportmonksId": 1158,
    "name": "4. Liga Division A",
    "shortName": "4. Liga Divisio",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1159,
    "sportmonksId": 1159,
    "name": "4. Liga Division B",
    "shortName": "4. Liga Divisio",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1160,
    "sportmonksId": 1160,
    "name": "4. Liga Division C",
    "shortName": "4. Liga Divisio",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1161,
    "sportmonksId": 1161,
    "name": "4. Liga Division E",
    "shortName": "4. Liga Divisio",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1162,
    "sportmonksId": 1162,
    "name": "4. Liga Division D",
    "shortName": "4. Liga Divisio",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1172,
    "sportmonksId": 1172,
    "name": "Kakkonen",
    "shortName": "Kakkonen",
    "country": "Finland",
    "countryCode": "FI",
    "emoji": "🇫🇮",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1176,
    "sportmonksId": 1176,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1219,
    "sportmonksId": 1219,
    "name": "2. Division: Group 2",
    "shortName": "2. Division: Gr",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1224,
    "sportmonksId": 1224,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "Portugal",
    "countryCode": "PT",
    "emoji": "🇵🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1251,
    "sportmonksId": 1251,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "Spain",
    "countryCode": "ES",
    "emoji": "🇪🇸",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1276,
    "sportmonksId": 1276,
    "name": "Division 2: Norra Gotaland",
    "shortName": "Division 2: Nor",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1277,
    "sportmonksId": 1277,
    "name": "Division 2: Norra Svealand",
    "shortName": "Division 2: Nor",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1278,
    "sportmonksId": 1278,
    "name": "Division 2: Norrland",
    "shortName": "Division 2: Nor",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1281,
    "sportmonksId": 1281,
    "name": "Division 2: Vastra Gotaland",
    "shortName": "Division 2: Vas",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1288,
    "sportmonksId": 1288,
    "name": "Acreano",
    "shortName": "Acreano",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1291,
    "sportmonksId": 1291,
    "name": "Baiano 1",
    "shortName": "Baiano 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1292,
    "sportmonksId": 1292,
    "name": "Baiano 2",
    "shortName": "Baiano 2",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1294,
    "sportmonksId": 1294,
    "name": "Copa do Nordeste",
    "shortName": "Copa do Nordest",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1296,
    "sportmonksId": 1296,
    "name": "Carioca Serie A",
    "shortName": "Carioca Serie A",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1300,
    "sportmonksId": 1300,
    "name": "Cearense 1",
    "shortName": "Cearense 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1302,
    "sportmonksId": 1302,
    "name": "Gaucho 1",
    "shortName": "Gaucho 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1307,
    "sportmonksId": 1307,
    "name": "Mineiro 1",
    "shortName": "Mineiro 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1311,
    "sportmonksId": 1311,
    "name": "Paranaense 1",
    "shortName": "Paranaense 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1313,
    "sportmonksId": 1313,
    "name": "Paulista A1",
    "shortName": "Paulista A1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1316,
    "sportmonksId": 1316,
    "name": "Pernambucano 1",
    "shortName": "Pernambucano 1",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1324,
    "sportmonksId": 1324,
    "name": "Amapaense",
    "shortName": "Amapaense",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1325,
    "sportmonksId": 1325,
    "name": "Euro Qualification",
    "shortName": "Euro Qualificat",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1326,
    "sportmonksId": 1326,
    "name": "European Championship",
    "shortName": "European Champi",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1327,
    "sportmonksId": 1327,
    "name": "Euro U21",
    "shortName": "Euro U21",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1328,
    "sportmonksId": 1328,
    "name": "UEFA Super Cup",
    "shortName": "UEFA Super Cup",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1333,
    "sportmonksId": 1333,
    "name": "Torneo Federal A",
    "shortName": "Torneo Federal ",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1355,
    "sportmonksId": 1355,
    "name": "Euro U19",
    "shortName": "Euro U19",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1356,
    "sportmonksId": 1356,
    "name": "A-League Men",
    "shortName": "A-League Men",
    "country": "Australia",
    "countryCode": "AU",
    "emoji": "🇦🇺",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1362,
    "sportmonksId": 1362,
    "name": "K League 2",
    "shortName": "K League 2",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1363,
    "sportmonksId": 1363,
    "name": "Friendly International Women",
    "shortName": "Friendly Intern",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1364,
    "sportmonksId": 1364,
    "name": "World Cup U20",
    "shortName": "World Cup U20",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1368,
    "sportmonksId": 1368,
    "name": "Tournoi Maurice Revello",
    "shortName": "Tournoi Maurice",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1369,
    "sportmonksId": 1369,
    "name": "World Cup Women",
    "shortName": "World Cup Women",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1379,
    "sportmonksId": 1379,
    "name": "Cosafa Cup",
    "shortName": "Cosafa Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1385,
    "sportmonksId": 1385,
    "name": "Brasileiro U20",
    "shortName": "Brasileiro U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1389,
    "sportmonksId": 1389,
    "name": "UEFA Women\\'s EURO",
    "shortName": "UEFA Women\\'s EU",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1403,
    "sportmonksId": 1403,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1412,
    "sportmonksId": 1412,
    "name": "Egypt Cup",
    "shortName": "Egypt Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1460,
    "sportmonksId": 1460,
    "name": "Moravskoslezsky Kp",
    "shortName": "Moravskoslezsky",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1461,
    "sportmonksId": 1461,
    "name": "Olomoucky Kp",
    "shortName": "Olomoucky Kp",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1462,
    "sportmonksId": 1462,
    "name": "Jihomoravsky Kp",
    "shortName": "Jihomoravsky Kp",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1465,
    "sportmonksId": 1465,
    "name": "Kralovehradecky Kp",
    "shortName": "Kralovehradecky",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1466,
    "sportmonksId": 1466,
    "name": "Liberecky Kp",
    "shortName": "Liberecky Kp",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1469,
    "sportmonksId": 1469,
    "name": "Jihocesky Kp",
    "shortName": "Jihocesky Kp",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1479,
    "sportmonksId": 1479,
    "name": "Concacaf League",
    "shortName": "Concacaf League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1502,
    "sportmonksId": 1502,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1512,
    "sportmonksId": 1512,
    "name": "Regionalliga: West",
    "shortName": "Regionalliga: W",
    "country": "Austria",
    "countryCode": "AT",
    "emoji": "🇦🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1538,
    "sportmonksId": 1538,
    "name": "UEFA Nations League",
    "shortName": "UEFA Nations Le",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1546,
    "sportmonksId": 1546,
    "name": "Central American & Caribbean Games",
    "shortName": "Central America",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1548,
    "sportmonksId": 1548,
    "name": "Elitettan Women",
    "shortName": "Elitettan Women",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1552,
    "sportmonksId": 1552,
    "name": "Svenska Cupen Women",
    "shortName": "Svenska Cupen W",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1554,
    "sportmonksId": 1554,
    "name": "Kansallinen Liiga Women",
    "shortName": "Kansallinen Lii",
    "country": "Finland",
    "countryCode": "FI",
    "emoji": "🇫🇮",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1555,
    "sportmonksId": 1555,
    "name": "Asian Games",
    "shortName": "Asian Games",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1557,
    "sportmonksId": 1557,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1561,
    "sportmonksId": 1561,
    "name": "3. Division - Group 1",
    "shortName": "3. Division - G",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1568,
    "sportmonksId": 1568,
    "name": "Primera Division Women",
    "shortName": "Primera Divisio",
    "country": "Spain",
    "countryCode": "ES",
    "emoji": "🇪🇸",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1578,
    "sportmonksId": 1578,
    "name": "Serie A Women",
    "shortName": "Serie A Women",
    "country": "Italy",
    "countryCode": "IT",
    "emoji": "🇮🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1583,
    "sportmonksId": 1583,
    "name": "A-League Women",
    "shortName": "A-League Women",
    "country": "Australia",
    "countryCode": "AU",
    "emoji": "🇦🇺",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1607,
    "sportmonksId": 1607,
    "name": "USL League One",
    "shortName": "USL League One",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1631,
    "sportmonksId": 1631,
    "name": "Brasileiro Women",
    "shortName": "Brasileiro Wome",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1645,
    "sportmonksId": 1645,
    "name": "Super League",
    "shortName": "Super League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1658,
    "sportmonksId": 1658,
    "name": "Copa de la Superliga",
    "shortName": "Copa de la Supe",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1671,
    "sportmonksId": 1671,
    "name": "Nadeshiko League 1",
    "shortName": "Nadeshiko Leagu",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1684,
    "sportmonksId": 1684,
    "name": "Paulista U20",
    "shortName": "Paulista U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1685,
    "sportmonksId": 1685,
    "name": "Mineiro U20",
    "shortName": "Mineiro U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1687,
    "sportmonksId": 1687,
    "name": "Catarinense 2",
    "shortName": "Catarinense 2",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1689,
    "sportmonksId": 1689,
    "name": "Premier League",
    "shortName": "Premier League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1690,
    "sportmonksId": 1690,
    "name": "King\\'s Cup",
    "shortName": "King\\'s Cup",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1691,
    "sportmonksId": 1691,
    "name": "Premier League - Playoffs",
    "shortName": "Premier League ",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": true
  },
  {
    "id": 1693,
    "sportmonksId": 1693,
    "name": "4. Deild",
    "shortName": "4. Deild",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1695,
    "sportmonksId": 1695,
    "name": "Landesliga: Vorarlberg",
    "shortName": "Landesliga: Vor",
    "country": "Austria",
    "countryCode": "AT",
    "emoji": "🇦🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1699,
    "sportmonksId": 1699,
    "name": "Segunda División",
    "shortName": "Segunda Divisió",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1714,
    "sportmonksId": 1714,
    "name": "Pacific Games",
    "shortName": "Pacific Games",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1719,
    "sportmonksId": 1719,
    "name": "Japan Football League",
    "shortName": "Japan Football ",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1729,
    "sportmonksId": 1729,
    "name": "Southeast Asian Games",
    "shortName": "Southeast Asian",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 1741,
    "sportmonksId": 1741,
    "name": "CONCACAF Nations League",
    "shortName": "CONCACAF Nation",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1742,
    "sportmonksId": 1742,
    "name": "CONCACAF Nations League Qualification",
    "shortName": "CONCACAF Nation",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1746,
    "sportmonksId": 1746,
    "name": "Copa Paulista",
    "shortName": "Copa Paulista",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1772,
    "sportmonksId": 1772,
    "name": "Federation Cup",
    "shortName": "Federation Cup",
    "country": "Bangladesh",
    "countryCode": "BD",
    "emoji": "🇧🇩",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1784,
    "sportmonksId": 1784,
    "name": "CONMEBOL Pre-Olympic Tournament",
    "shortName": "CONMEBOL Pre-Ol",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1797,
    "sportmonksId": 1797,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1798,
    "sportmonksId": 1798,
    "name": "Supercopa do Brasil",
    "shortName": "Supercopa do Br",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1804,
    "sportmonksId": 1804,
    "name": "NPSL",
    "shortName": "NPSL",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1818,
    "sportmonksId": 1818,
    "name": "Landesliga: Niederösterreich",
    "shortName": "Landesliga: Nie",
    "country": "Austria",
    "countryCode": "AT",
    "emoji": "🇦🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1819,
    "sportmonksId": 1819,
    "name": "Landesliga: Oberösterreich",
    "shortName": "Landesliga: Obe",
    "country": "Austria",
    "countryCode": "AT",
    "emoji": "🇦🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1880,
    "sportmonksId": 1880,
    "name": "Esiliiga B",
    "shortName": "Esiliiga B",
    "country": "Estonia",
    "countryCode": "EE",
    "emoji": "🇪🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1885,
    "sportmonksId": 1885,
    "name": "Nwsl Challenge Cup Women",
    "shortName": "Nwsl Challenge ",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1989,
    "sportmonksId": 1989,
    "name": "Qatar Prince Cup",
    "shortName": "Qatar Prince Cu",
    "country": "Qatar",
    "countryCode": "QA",
    "emoji": "🇶🇦",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 1990,
    "sportmonksId": 1990,
    "name": "Super Cup",
    "shortName": "Super Cup",
    "country": "UAE",
    "countryCode": "AE",
    "emoji": "🇦🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2006,
    "sportmonksId": 2006,
    "name": "Copa Do Nordeste U20",
    "shortName": "Copa Do Nordest",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2040,
    "sportmonksId": 2040,
    "name": "Olympic Qualifying Concacaf",
    "shortName": "Olympic Qualify",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2286,
    "sportmonksId": 2286,
    "name": "Europa Conference League",
    "shortName": "Europa Conferen",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 2294,
    "sportmonksId": 2294,
    "name": "Brasileiro Feminino A2",
    "shortName": "Brasileiro Femi",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2312,
    "sportmonksId": 2312,
    "name": "WPSL",
    "shortName": "WPSL",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2321,
    "sportmonksId": 2321,
    "name": "CONCACAF Gold Cup Qualification",
    "shortName": "CONCACAF Gold C",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2324,
    "sportmonksId": 2324,
    "name": "Brasiliense U20",
    "shortName": "Brasiliense U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2325,
    "sportmonksId": 2325,
    "name": "Amazonense U20",
    "shortName": "Amazonense U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2328,
    "sportmonksId": 2328,
    "name": "NWSL",
    "shortName": "NWSL",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2368,
    "sportmonksId": 2368,
    "name": "Sergipano U20",
    "shortName": "Sergipano U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2402,
    "sportmonksId": 2402,
    "name": "Pernambucano U20",
    "shortName": "Pernambucano U2",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2407,
    "sportmonksId": 2407,
    "name": "Federation Cup",
    "shortName": "Federation Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2411,
    "sportmonksId": 2411,
    "name": "Goiano U20",
    "shortName": "Goiano U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2432,
    "sportmonksId": 2432,
    "name": "Federation Cup",
    "shortName": "Federation Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2450,
    "sportmonksId": 2450,
    "name": "Club Friendlies 2",
    "shortName": "Club Friendlies",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 2451,
    "sportmonksId": 2451,
    "name": "Club Friendlies 3",
    "shortName": "Club Friendlies",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 2452,
    "sportmonksId": 2452,
    "name": "Club Friendlies 4",
    "shortName": "Club Friendlies",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 2516,
    "sportmonksId": 2516,
    "name": "Paraense U20",
    "shortName": "Paraense U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2518,
    "sportmonksId": 2518,
    "name": "3. Division - Group 2",
    "shortName": "3. Division - G",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2519,
    "sportmonksId": 2519,
    "name": "3. Division - Group 3",
    "shortName": "3. Division - G",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2520,
    "sportmonksId": 2520,
    "name": "3. Division - Group 4",
    "shortName": "3. Division - G",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2521,
    "sportmonksId": 2521,
    "name": "3. Division - Group 5",
    "shortName": "3. Division - G",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2522,
    "sportmonksId": 2522,
    "name": "3. Division - Group 6",
    "shortName": "3. Division - G",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2528,
    "sportmonksId": 2528,
    "name": "League Cup",
    "shortName": "League Cup",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2545,
    "sportmonksId": 2545,
    "name": "MLS Next Pro",
    "shortName": "MLS Next Pro",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2585,
    "sportmonksId": 2585,
    "name": "League Two",
    "shortName": "League Two",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2599,
    "sportmonksId": 2599,
    "name": "Paranaense U20",
    "shortName": "Paranaense U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2606,
    "sportmonksId": 2606,
    "name": "USL W League",
    "shortName": "USL W League",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2679,
    "sportmonksId": 2679,
    "name": "African Nations Championship Qualification",
    "shortName": "African Nations",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2694,
    "sportmonksId": 2694,
    "name": "Potiguar U20",
    "shortName": "Potiguar U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2707,
    "sportmonksId": 2707,
    "name": "Brasileiro Feminino A3",
    "shortName": "Brasileiro Femi",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2711,
    "sportmonksId": 2711,
    "name": "Brasileiro U17",
    "shortName": "Brasileiro U17",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2763,
    "sportmonksId": 2763,
    "name": "Maranhense 2",
    "shortName": "Maranhense 2",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 3081,
    "sportmonksId": 3081,
    "name": "Brasileiro Women U20",
    "shortName": "Brasileiro Wome",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 3124,
    "sportmonksId": 3124,
    "name": "Cearense U20",
    "shortName": "Cearense U20",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 3232,
    "sportmonksId": 3232,
    "name": "Olympic Qualifying: Oceania",
    "shortName": "Olympic Qualify",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 3306,
    "sportmonksId": 3306,
    "name": "Ykkönen",
    "shortName": "Ykkönen",
    "country": "Finland",
    "countryCode": "FI",
    "emoji": "🇫🇮",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 3320,
    "sportmonksId": 3320,
    "name": "All Africa Games",
    "shortName": "All Africa Game",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 3360,
    "sportmonksId": 3360,
    "name": "Olympics Intercontinental Play-offs",
    "shortName": "Olympics Interc",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 3412,
    "sportmonksId": 3412,
    "name": "FIFA Club World Cup",
    "shortName": "FIFA Club World",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 3431,
    "sportmonksId": 3431,
    "name": "EAFF Football Championship Qualification",
    "shortName": "EAFF Football C",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 3469,
    "sportmonksId": 3469,
    "name": "Brasileiro U20 B",
    "shortName": "Brasileiro U20 ",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 3516,
    "sportmonksId": 3516,
    "name": "II Lyga",
    "shortName": "II Lyga",
    "country": "World",
    "countryCode": "WLD",
    "emoji": "⚽",
    "isInternational": false,
    "isCup": false
  }
];

export const CRICKET_LEAGUES: TrackedLeague[] = [
  {
    "id": 1,
    "sportmonksId": 1,
    "name": "Indian Premier League",
    "shortName": "IPL",
    "country": "India",
    "countryCode": "IN",
    "emoji": "🇮🇳",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 2,
    "sportmonksId": 2,
    "name": "One Day International",
    "shortName": "ODI",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 3,
    "sportmonksId": 3,
    "name": "Twenty20 International",
    "shortName": "T20I",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 4,
    "sportmonksId": 4,
    "name": "Test Series",
    "shortName": "TEST",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 5,
    "sportmonksId": 5,
    "name": "Big Bash League",
    "shortName": "BBL",
    "country": "Australia",
    "countryCode": "AU",
    "emoji": "🇦🇺",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 6,
    "sportmonksId": 6,
    "name": "Super Smash",
    "shortName": "SS",
    "country": "New Zealand",
    "countryCode": "NZ",
    "emoji": "🇳🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 7,
    "sportmonksId": 7,
    "name": "Afghanistan Premier League",
    "shortName": "APL",
    "country": "Afghanistan",
    "countryCode": "AF",
    "emoji": "🇦🇫",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 8,
    "sportmonksId": 8,
    "name": "Pakistan Super League",
    "shortName": "PSL",
    "country": "Pakistan",
    "countryCode": "PK",
    "emoji": "🇵🇰",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 9,
    "sportmonksId": 9,
    "name": "Bangladesh Premier League",
    "shortName": "BPL",
    "country": "Bangladesh",
    "countryCode": "BD",
    "emoji": "🇧🇩",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 10,
    "sportmonksId": 10,
    "name": "CSA T20 Challenge",
    "shortName": "T20C",
    "country": "South Africa",
    "countryCode": "ZA",
    "emoji": "🇿🇦",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 11,
    "sportmonksId": 11,
    "name": "Asia Cup",
    "shortName": "AC",
    "country": "Asia",
    "countryCode": "ASIA",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 12,
    "sportmonksId": 12,
    "name": "Ashes Series",
    "shortName": "ASH",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 13,
    "sportmonksId": 13,
    "name": "T20 Blast",
    "shortName": "T20B",
    "country": "England",
    "countryCode": "GB",
    "emoji": "🇬🇧",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 14,
    "sportmonksId": 14,
    "name": "Pro50 Championship",
    "shortName": "PC",
    "country": "Zimbabwe",
    "countryCode": "ZW",
    "emoji": "🇿🇼",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 15,
    "sportmonksId": 15,
    "name": "Logan Cup",
    "shortName": "LC",
    "country": "Zimbabwe",
    "countryCode": "ZW",
    "emoji": "🇿🇼",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 16,
    "sportmonksId": 16,
    "name": "ICC Women\\'s T20 World Cup",
    "shortName": "WWCT20",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 17,
    "sportmonksId": 17,
    "name": "ICC Men\\'s T20 World Cup",
    "shortName": "WCT20",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 18,
    "sportmonksId": 18,
    "name": "ICC World Cup",
    "shortName": "WC",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 19,
    "sportmonksId": 19,
    "name": "Women\\'s Cricket Super League",
    "shortName": "WCSL",
    "country": "England",
    "countryCode": "GB",
    "emoji": "🇬🇧",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 22,
    "sportmonksId": 22,
    "name": "UAE T20x",
    "shortName": "UAET20X",
    "country": "UAE",
    "countryCode": "AE",
    "emoji": "🇦🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 23,
    "sportmonksId": 23,
    "name": "Abu Dhabi T10 League",
    "shortName": "T10",
    "country": "UAE",
    "countryCode": "AE",
    "emoji": "🇦🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 29,
    "sportmonksId": 29,
    "name": "Sheffield Shield",
    "shortName": "SS",
    "country": "Australia",
    "countryCode": "AU",
    "emoji": "🇦🇺",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 32,
    "sportmonksId": 32,
    "name": "One-Day Cup",
    "shortName": "ODC",
    "country": "Australia",
    "countryCode": "AU",
    "emoji": "🇦🇺",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 35,
    "sportmonksId": 35,
    "name": "Tri-Series",
    "shortName": "TS",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 41,
    "sportmonksId": 41,
    "name": "ICC Champions Trophy",
    "shortName": "CT",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 47,
    "sportmonksId": 47,
    "name": "County Championship Division One",
    "shortName": "D1",
    "country": "England",
    "countryCode": "GB",
    "emoji": "🇬🇧",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 83,
    "sportmonksId": 83,
    "name": "European T20 Premier League",
    "shortName": "ETPL",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 86,
    "sportmonksId": 86,
    "name": "ICC World Cup Warm-up Matches",
    "shortName": "WM",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 100,
    "sportmonksId": 100,
    "name": "Super Provincial One Day Tournament",
    "shortName": "SPOD",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🏏",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 106,
    "sportmonksId": 106,
    "name": "T20 Mumbai",
    "shortName": "T20M",
    "country": "India",
    "countryCode": "IN",
    "emoji": "🇮🇳",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 138,
    "sportmonksId": 138,
    "name": "The Hundred",
    "shortName": "TH",
    "country": "England",
    "countryCode": "GB",
    "emoji": "🇬🇧",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 141,
    "sportmonksId": 141,
    "name": "The Women\\'s Hundred",
    "shortName": "THW",
    "country": "England",
    "countryCode": "GB",
    "emoji": "🇬🇧",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 150,
    "sportmonksId": 150,
    "name": "Qatar T10 League",
    "shortName": "QT10L",
    "country": "Qatar",
    "countryCode": "QA",
    "emoji": "🇶🇦",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 168,
    "sportmonksId": 168,
    "name": "Finnish Premier League",
    "shortName": "FPL",
    "country": "Finland",
    "countryCode": "FI",
    "emoji": "🇫🇮",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 171,
    "sportmonksId": 171,
    "name": "European Cricket Series Sweden",
    "shortName": "ECS",
    "country": "Sweden",
    "countryCode": "SE",
    "emoji": "🇸🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 177,
    "sportmonksId": 177,
    "name": "European Cricket Series St Gallen",
    "shortName": "ECS",
    "country": "Switzerland",
    "countryCode": "CH",
    "emoji": "🇨🇭",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 180,
    "sportmonksId": 180,
    "name": "European Cricket Series Kummerfeld",
    "shortName": "ECS",
    "country": "Germany",
    "countryCode": "DE",
    "emoji": "🇩🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 183,
    "sportmonksId": 183,
    "name": "European Cricket Series Frankfurt",
    "shortName": "ECS",
    "country": "Germany",
    "countryCode": "DE",
    "emoji": "🇩🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 186,
    "sportmonksId": 186,
    "name": "European Cricket Series Cyprus T10 League",
    "shortName": "ECS",
    "country": "Cyprus",
    "countryCode": "CY",
    "emoji": "🇨🇾",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 189,
    "sportmonksId": 189,
    "name": "European Cricket Series Tallinn",
    "shortName": "ECS",
    "country": "Estonia",
    "countryCode": "EE",
    "emoji": "🇪🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 201,
    "sportmonksId": 201,
    "name": "ICC Cricket World Cup Super League",
    "shortName": "WCSL",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 204,
    "sportmonksId": 204,
    "name": "European Cricket Series Finland",
    "shortName": "ECS",
    "country": "Finland",
    "countryCode": "FI",
    "emoji": "🇫🇮",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 216,
    "sportmonksId": 216,
    "name": "European Cricket Series Belgium",
    "shortName": "ECS",
    "country": "Belgium",
    "countryCode": "BE",
    "emoji": "🇧🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 222,
    "sportmonksId": 222,
    "name": "European Cricket Series Dresden",
    "shortName": "ESC",
    "country": "Germany",
    "countryCode": "DE",
    "emoji": "🇩🇪",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 225,
    "sportmonksId": 225,
    "name": "European Cricket Series Vienna",
    "shortName": "ECS",
    "country": "Austria",
    "countryCode": "AT",
    "emoji": "🇦🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 228,
    "sportmonksId": 228,
    "name": "European Cricket Series Hungary",
    "shortName": "ECS",
    "country": "Hungary",
    "countryCode": "HU",
    "emoji": "🇭🇺",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 231,
    "sportmonksId": 231,
    "name": "European Cricket Series Cyprus",
    "shortName": "ECS",
    "country": "Cyprus",
    "countryCode": "CY",
    "emoji": "🇨🇾",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 234,
    "sportmonksId": 234,
    "name": "European Cricket Series Rome",
    "shortName": "ECS",
    "country": "Italy",
    "countryCode": "IT",
    "emoji": "🇮🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 237,
    "sportmonksId": 237,
    "name": "European Cricket Series Bulgaria",
    "shortName": "ECS",
    "country": "Bulgaria",
    "countryCode": "BG",
    "emoji": "🇧🇬",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 243,
    "sportmonksId": 243,
    "name": "European Cricket Series Romania",
    "shortName": "ECS",
    "country": "Romania",
    "countryCode": "RO",
    "emoji": "🇷🇴",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 249,
    "sportmonksId": 249,
    "name": "European Cricket Series Capelle",
    "shortName": "ECS",
    "country": "Netherlands",
    "countryCode": "NL",
    "emoji": "🇳🇱",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 252,
    "sportmonksId": 252,
    "name": "European Cricket Series Portugal",
    "shortName": "ECS",
    "country": "Portugal",
    "countryCode": "PT",
    "emoji": "🇵🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 255,
    "sportmonksId": 255,
    "name": "Jharkhand T20 League",
    "shortName": "JKL",
    "country": "India",
    "countryCode": "IN",
    "emoji": "🇮🇳",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 258,
    "sportmonksId": 258,
    "name": "Twenty20 International Women",
    "shortName": "T20IW",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 261,
    "sportmonksId": 261,
    "name": "One Day International Women",
    "shortName": "ODIW",
    "country": "International",
    "countryCode": "INT",
    "emoji": "🌍",
    "isInternational": true,
    "isCup": true
  },
  {
    "id": 264,
    "sportmonksId": 264,
    "name": "European Cricket Series Czech Republic",
    "shortName": "ECS",
    "country": "Czech Republic",
    "countryCode": "CZ",
    "emoji": "🇨🇿",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 270,
    "sportmonksId": 270,
    "name": "European Cricket Series Barcelona",
    "shortName": "ECS",
    "country": "Spain",
    "countryCode": "ES",
    "emoji": "🇪🇸",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 276,
    "sportmonksId": 276,
    "name": "Andhra T20 League",
    "shortName": "AT20",
    "country": "India",
    "countryCode": "IN",
    "emoji": "🇮🇳",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 282,
    "sportmonksId": 282,
    "name": "European Cricket Series Malta",
    "shortName": "ECS",
    "country": "Malta",
    "countryCode": "MT",
    "emoji": "🇲🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 288,
    "sportmonksId": 288,
    "name": "Bengal T20 Challenge",
    "shortName": "BTC",
    "country": "India",
    "countryCode": "IN",
    "emoji": "🇮🇳",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 294,
    "sportmonksId": 294,
    "name": "European Cricket League",
    "shortName": "ECL",
    "country": "Europe",
    "countryCode": "EU",
    "emoji": "🇪🇺",
    "isInternational": true,
    "isCup": false
  },
  {
    "id": 314,
    "sportmonksId": 314,
    "name": "European Cricket Series Venice",
    "shortName": "ECS",
    "country": "Italy",
    "countryCode": "IT",
    "emoji": "🇮🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 317,
    "sportmonksId": 317,
    "name": "European Cricket Series Milan",
    "shortName": "ECS",
    "country": "Italy",
    "countryCode": "IT",
    "emoji": "🇮🇹",
    "isInternational": false,
    "isCup": false
  },
  {
    "id": 320,
    "sportmonksId": 320,
    "name": "Portugal T10",
    "shortName": "ECN",
    "country": "Portugal",
    "countryCode": "PT",
    "emoji": "🇵🇹",
    "isInternational": false,
    "isCup": false
  }
];

// In-place mutable arrays and objects to maintain reactive compatibility across imports
export const DEFAULT_LEAGUES: TrackedLeague[] = [];
export const DEFAULT_LEAGUE_IDS: number[] = [];
export const LEAGUE_TO_SPORTMONKS: Record<number, number> = {};
export const SPORTMONKS_TO_LEAGUE: Record<number, number> = {};

export const getLeagueById = (id: number): TrackedLeague | undefined => {
  return DEFAULT_LEAGUES.find((l) => l.id === id);
};

// Helper to update arrays/records in place based on selected sport
export const updateTrackedLeagues = (sport: string) => {
  const source = sport === 'cricket' ? CRICKET_LEAGUES : FOOTBALL_LEAGUES;

  // Clear and update DEFAULT_LEAGUES
  DEFAULT_LEAGUES.length = 0;
  DEFAULT_LEAGUES.push(...source);

  // Clear and update DEFAULT_LEAGUE_IDS
  DEFAULT_LEAGUE_IDS.length = 0;
  DEFAULT_LEAGUE_IDS.push(...DEFAULT_LEAGUES.map((l) => l.id));

  // Clear and update LEAGUE_TO_SPORTMONKS
  for (const key in LEAGUE_TO_SPORTMONKS) {
    delete LEAGUE_TO_SPORTMONKS[key];
  }
  // Clear and update SPORTMONKS_TO_LEAGUE
  for (const key in SPORTMONKS_TO_LEAGUE) {
    delete SPORTMONKS_TO_LEAGUE[key];
  }

  // Populate records
  source.forEach((l) => {
    LEAGUE_TO_SPORTMONKS[l.id] = l.sportmonksId;
    SPORTMONKS_TO_LEAGUE[l.sportmonksId] = l.id;
  });
};

import { useSettingsStore } from '@/store/settingsStore';

// Initialize
try {
  const currentSport = useSettingsStore.getState().settings.sport || 'football';
  updateTrackedLeagues(currentSport);
} catch {
  updateTrackedLeagues('football');
}

// Subscribe to store updates to dynamically adjust leagues
try {
  let prevSport = useSettingsStore.getState().settings.sport || 'football';
  useSettingsStore.subscribe(
    (state) => {
      const currentSport = state.settings.sport || 'football';
      if (currentSport !== prevSport) {
        prevSport = currentSport;
        updateTrackedLeagues(currentSport);
      }
    }
  );
} catch {}
