/**
 * Leagues tracked by BORO AI.
 *
 * Generated automatically from active plan subscriptions.
 */
export interface TrackedLeague {
  id: number;
  sportmonksId: number;
  name: string;
  shortName: string;
  country: string;
  countryCode?: string;
  emoji: string;
  isInternational?: boolean;
  isCup?: boolean;
}

export const DEFAULT_LEAGUES: TrackedLeague[] = [{ id: 2, sportmonksId: 2, name: 'Champions League', shortName: 'UCL', country: 'International', emoji: 'ðŸ†', isInternational: true, },
{ id: 3, sportmonksId: 5, name: 'Europa League', shortName: 'UEL', country: 'International', emoji: 'ðŸ†', isInternational: true, },
{ id: 39, sportmonksId: 8, name: 'Premier League', shortName: 'EPL', country: 'World', countryCode: 'GB', emoji: 'ðŸ´', },
{ id: 40, sportmonksId: 9, name: 'Championship', shortName: 'Champ', country: 'World', countryCode: 'GB', emoji: 'ðŸ´', },
{ id: 41, sportmonksId: 12, name: 'League One', shortName: 'L1 ENG', country: 'World', countryCode: 'GB', emoji: 'ðŸ´', },
{ id: 42, sportmonksId: 14, name: 'League Two', shortName: 'L2 ENG', country: 'World', countryCode: 'GB', emoji: 'ðŸ´', },
{ id: 20017, sportmonksId: 17, name: 'Enterprise National League', shortName: 'Enterprise Nati', country: 'World', emoji: 'âš½', },
{ id: 20020, sportmonksId: 20, name: 'Enterprise National League North', shortName: 'Enterprise Nati', country: 'World', emoji: 'âš½', },
{ id: 20023, sportmonksId: 23, name: 'Community Shield', shortName: 'Community Shiel', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 45, sportmonksId: 24, name: 'FA Cup', shortName: 'FA Cup', country: 'World', countryCode: 'GB', emoji: 'ðŸ´', isCup: true, },
{ id: 48, sportmonksId: 27, name: 'Carabao Cup', shortName: 'Carabao', country: 'World', countryCode: 'GB', emoji: 'ðŸ´', isCup: true, },
{ id: 20030, sportmonksId: 30, name: 'Fa Trophy', shortName: 'Fa Trophy', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20032, sportmonksId: 32, name: 'Premier League Cup', shortName: 'Premier League ', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20035, sportmonksId: 35, name: 'Premier League U21', shortName: 'Premier League ', country: 'World', emoji: 'âš½', },
{ id: 20038, sportmonksId: 38, name: 'Premier League International Cup', shortName: 'Premier League ', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20039, sportmonksId: 39, name: 'EFL Trophy', shortName: 'EFL Trophy', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20044, sportmonksId: 44, name: 'Wsl 2 Women', shortName: 'Wsl 2 Women', country: 'World', emoji: 'âš½', },
{ id: 20045, sportmonksId: 45, name: 'Women\'s Super League', shortName: 'Women\'s Super L', country: 'World', emoji: 'âš½', },
{ id: 88, sportmonksId: 72, name: 'Eredivisie', shortName: 'Eredivisie', country: 'World', countryCode: 'NL', emoji: 'ðŸ‡³ðŸ‡±', },
{ id: 20074, sportmonksId: 74, name: 'Eerste Divisie', shortName: 'Eerste Divisie', country: 'World', emoji: 'âš½', },
{ id: 20077, sportmonksId: 77, name: 'Tweede Divisie', shortName: 'Tweede Divisie', country: 'World', emoji: 'âš½', },
{ id: 20078, sportmonksId: 78, name: 'KNVB Beker', shortName: 'KNVB Beker', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 20081, sportmonksId: 81, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 78, sportmonksId: 82, name: 'Bundesliga', shortName: 'BuLi', country: 'World', countryCode: 'DE', emoji: 'ðŸ‡©ðŸ‡ª', },
{ id: 79, sportmonksId: 85, name: '2. Bundesliga', shortName: 'BuLi 2', country: 'World', countryCode: 'DE', emoji: 'ðŸ‡©ðŸ‡ª', },
{ id: 20088, sportmonksId: 88, name: '3. Liga', shortName: '3. Liga', country: 'World', emoji: 'âš½', },
{ id: 20091, sportmonksId: 91, name: 'Regionalliga: Nord', shortName: 'Regionalliga: N', country: 'World', emoji: 'âš½', },
{ id: 20094, sportmonksId: 94, name: 'Regionalliga: Bayern', shortName: 'Regionalliga: B', country: 'World', emoji: 'âš½', },
{ id: 20097, sportmonksId: 97, name: 'Regionalliga: Nordost', shortName: 'Regionalliga: N', country: 'World', emoji: 'âš½', },
{ id: 20103, sportmonksId: 103, name: 'Regionalliga: Südwest', shortName: 'Regionalliga: S', country: 'World', emoji: 'âš½', },
{ id: 20106, sportmonksId: 106, name: 'Regionalliga: West', shortName: 'Regionalliga: W', country: 'World', emoji: 'âš½', },
{ id: 81, sportmonksId: 109, name: 'DFB Pokal', shortName: 'DFB Pokal', country: 'World', countryCode: 'DE', emoji: 'ðŸ‡©ðŸ‡ª', isCup: true, },
{ id: 20163, sportmonksId: 163, name: 'Bundesliga Play-offs', shortName: 'Bundesliga Play', country: 'World', emoji: 'âš½', },
{ id: 20166, sportmonksId: 166, name: '2. Bundesliga Play-offs', shortName: '2. Bundesliga P', country: 'World', emoji: 'âš½', },
{ id: 20169, sportmonksId: 169, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20172, sportmonksId: 172, name: 'Superliga', shortName: 'Superliga', country: 'World', emoji: 'âš½', },
{ id: 20175, sportmonksId: 175, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 218, sportmonksId: 181, name: 'Admiral Bundesliga', shortName: 'Austria', country: 'World', countryCode: 'AT', emoji: 'ðŸ‡¦ðŸ‡¹', },
{ id: 20184, sportmonksId: 184, name: '2. Liga', shortName: '2. Liga', country: 'World', emoji: 'âš½', },
{ id: 20190, sportmonksId: 190, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 20199, sportmonksId: 199, name: 'Vysshaya Liga', shortName: 'Vysshaya Liga', country: 'World', emoji: 'âš½', },
{ id: 144, sportmonksId: 208, name: 'Pro League', shortName: 'Belgium', country: 'World', countryCode: 'BE', emoji: 'ðŸ‡§ðŸ‡ª', },
{ id: 20211, sportmonksId: 211, name: 'Challenger Pro League', shortName: 'Challenger Pro ', country: 'World', emoji: 'âš½', },
{ id: 20214, sportmonksId: 214, name: 'Belgian Cup', shortName: 'Belgian Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20220, sportmonksId: 220, name: 'Premier Liga', shortName: 'Premier Liga', country: 'World', emoji: 'âš½', },
{ id: 20229, sportmonksId: 229, name: 'First League', shortName: 'First League', country: 'World', emoji: 'âš½', },
{ id: 20247, sportmonksId: 247, name: '2. HNL', shortName: '2. HNL', country: 'World', emoji: 'âš½', },
{ id: 20253, sportmonksId: 253, name: '1. Division', shortName: '1. Division', country: 'World', emoji: 'âš½', },
{ id: 20262, sportmonksId: 262, name: 'Chance Liga', shortName: 'Chance Liga', country: 'World', emoji: 'âš½', },
{ id: 20265, sportmonksId: 265, name: 'Chance Národní Liga', shortName: 'Chance Národní ', country: 'World', emoji: 'âš½', },
{ id: 119, sportmonksId: 271, name: 'Superliga', shortName: 'Denmark', country: 'World', countryCode: 'DK', emoji: 'ðŸ‡©ðŸ‡°', },
{ id: 20274, sportmonksId: 274, name: 'First Division', shortName: 'First Division', country: 'World', emoji: 'âš½', },
{ id: 20286, sportmonksId: 286, name: 'Meistriliiga', shortName: 'Meistriliiga', country: 'World', emoji: 'âš½', },
{ id: 20292, sportmonksId: 292, name: 'Veikkausliiga', shortName: 'Veikkausliiga', country: 'World', emoji: 'âš½', },
{ id: 20295, sportmonksId: 295, name: 'Ykkösliiga', shortName: 'Ykkösliiga', country: 'World', emoji: 'âš½', },
{ id: 61, sportmonksId: 301, name: 'Ligue 1', shortName: 'Ligue 1', country: 'World', countryCode: 'FR', emoji: 'ðŸ‡«ðŸ‡·', },
{ id: 62, sportmonksId: 304, name: 'Ligue 2', shortName: 'Ligue 2', country: 'World', countryCode: 'FR', emoji: 'ðŸ‡«ðŸ‡·', },
{ id: 66, sportmonksId: 307, name: 'Coupe de France', shortName: 'Coupe FR', country: 'World', countryCode: 'FR', emoji: 'ðŸ‡«ðŸ‡·', isCup: true, },
{ id: 20310, sportmonksId: 310, name: 'Coupe de la Ligue', shortName: 'Coupe de la Lig', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 20313, sportmonksId: 313, name: 'National', shortName: 'National', country: 'World', emoji: 'âš½', },
{ id: 20319, sportmonksId: 319, name: 'Crystalbet Erovnuli Liga', shortName: 'Crystalbet Erov', country: 'World', emoji: 'âš½', },
{ id: 197, sportmonksId: 325, name: 'Super League', shortName: 'Greece', country: 'World', countryCode: 'GR', emoji: 'ðŸ‡¬ðŸ‡·', },
{ id: 20334, sportmonksId: 334, name: 'NB I', shortName: 'NB I', country: 'World', emoji: 'âš½', },
{ id: 20345, sportmonksId: 345, name: 'Besta deild', shortName: 'Besta deild', country: 'World', emoji: 'âš½', },
{ id: 20360, sportmonksId: 360, name: 'Premier Division', shortName: 'Premier Divisio', country: 'World', emoji: 'âš½', },
{ id: 20363, sportmonksId: 363, name: 'First Division', shortName: 'First Division', country: 'World', emoji: 'âš½', },
{ id: 20372, sportmonksId: 372, name: 'Ligat ha\'Al', shortName: 'Ligat ha\'Al', country: 'World', emoji: 'âš½', },
{ id: 20375, sportmonksId: 375, name: 'Liga Leumit', shortName: 'Liga Leumit', country: 'World', emoji: 'âš½', },
{ id: 135, sportmonksId: 384, name: 'Serie A', shortName: 'Serie A', country: 'World', countryCode: 'IT', emoji: 'ðŸ‡®ðŸ‡¹', },
{ id: 136, sportmonksId: 387, name: 'Serie B', shortName: 'Serie B', country: 'World', countryCode: 'IT', emoji: 'ðŸ‡®ðŸ‡¹', },
{ id: 137, sportmonksId: 390, name: 'Coppa Italia', shortName: 'Coppa IT', country: 'World', countryCode: 'IT', emoji: 'ðŸ‡®ðŸ‡¹', isCup: true, },
{ id: 20393, sportmonksId: 393, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 20399, sportmonksId: 399, name: 'Virsliga', shortName: 'Virsliga', country: 'World', emoji: 'âš½', },
{ id: 20405, sportmonksId: 405, name: 'A Lyga', shortName: 'A Lyga', country: 'World', emoji: 'âš½', },
{ id: 20420, sportmonksId: 420, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 20432, sportmonksId: 432, name: 'First League', shortName: 'First League', country: 'World', emoji: 'âš½', },
{ id: 20438, sportmonksId: 438, name: 'Premiership', shortName: 'Premiership', country: 'World', emoji: 'âš½', },
{ id: 103, sportmonksId: 444, name: 'Eliteserien', shortName: 'Norway', country: 'World', countryCode: 'NO', emoji: 'ðŸ‡³ðŸ‡´', },
{ id: 20447, sportmonksId: 447, name: '1. Division', shortName: '1. Division', country: 'World', emoji: 'âš½', },
{ id: 106, sportmonksId: 453, name: 'Ekstraklasa', shortName: 'Poland', country: 'World', countryCode: 'PL', emoji: 'ðŸ‡µðŸ‡±', },
{ id: 20456, sportmonksId: 456, name: '1. Liga', shortName: '1. Liga', country: 'World', emoji: 'âš½', },
{ id: 20459, sportmonksId: 459, name: 'Polish Cup', shortName: 'Polish Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 94, sportmonksId: 462, name: 'Liga Portugal', shortName: 'Liga PT', country: 'World', countryCode: 'PT', emoji: 'ðŸ‡µðŸ‡¹', },
{ id: 20465, sportmonksId: 465, name: 'Liga Portugal 2', shortName: 'Liga Portugal 2', country: 'World', emoji: 'âš½', },
{ id: 20468, sportmonksId: 468, name: 'Taça De Portugal', shortName: 'Taça De Portuga', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 20471, sportmonksId: 471, name: 'Taça da Liga', shortName: 'Taça da Liga', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 20474, sportmonksId: 474, name: 'Superliga', shortName: 'Superliga', country: 'World', emoji: 'âš½', },
{ id: 235, sportmonksId: 486, name: 'Premier League', shortName: 'Russia', country: 'World', countryCode: 'RU', emoji: 'ðŸ‡·ðŸ‡º', },
{ id: 20489, sportmonksId: 489, name: 'FNL', shortName: 'FNL', country: 'World', emoji: 'âš½', },
{ id: 20492, sportmonksId: 492, name: 'Russian Cup', shortName: 'Russian Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20498, sportmonksId: 498, name: 'Youth League', shortName: 'Youth League', country: 'World', emoji: 'âš½', },
{ id: 179, sportmonksId: 501, name: 'Premiership', shortName: 'Scotland', country: 'World', countryCode: 'GB', emoji: 'ðŸ´', },
{ id: 20504, sportmonksId: 504, name: 'Championship', shortName: 'Championship', country: 'World', emoji: 'âš½', },
{ id: 20507, sportmonksId: 507, name: 'Scottish Cup', shortName: 'Scottish Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20510, sportmonksId: 510, name: 'League Cup', shortName: 'League Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20513, sportmonksId: 513, name: 'Premiership Play-Offs', shortName: 'Premiership Pla', country: 'World', emoji: 'âš½', },
{ id: 20516, sportmonksId: 516, name: 'League One', shortName: 'League One', country: 'World', emoji: 'âš½', },
{ id: 20519, sportmonksId: 519, name: 'League Two', shortName: 'League Two', country: 'World', emoji: 'âš½', },
{ id: 20531, sportmonksId: 531, name: 'Super Liga', shortName: 'Super Liga', country: 'World', emoji: 'âš½', },
{ id: 20534, sportmonksId: 534, name: 'Prva Liga', shortName: 'Prva Liga', country: 'World', emoji: 'âš½', },
{ id: 20540, sportmonksId: 540, name: 'Niké Liga', shortName: 'Niké Liga', country: 'World', emoji: 'âš½', },
{ id: 20555, sportmonksId: 555, name: '1. SNL', shortName: '1. SNL', country: 'World', emoji: 'âš½', },
{ id: 140, sportmonksId: 564, name: 'La Liga', shortName: 'LaLiga', country: 'World', countryCode: 'ES', emoji: 'ðŸ‡ªðŸ‡¸', },
{ id: 141, sportmonksId: 567, name: 'La Liga 2', shortName: 'LaLiga2', country: 'World', countryCode: 'ES', emoji: 'ðŸ‡ªðŸ‡¸', },
{ id: 143, sportmonksId: 570, name: 'Copa Del Rey', shortName: 'Copa Rey', country: 'World', countryCode: 'ES', emoji: 'ðŸ‡ªðŸ‡¸', isCup: true, },
{ id: 113, sportmonksId: 573, name: 'Allsvenskan', shortName: 'Sweden', country: 'World', countryCode: 'SE', emoji: 'ðŸ‡¸ðŸ‡ª', },
{ id: 20576, sportmonksId: 576, name: 'Damallsvenskan', shortName: 'Damallsvenskan', country: 'World', emoji: 'âš½', },
{ id: 20579, sportmonksId: 579, name: 'Superettan', shortName: 'Superettan', country: 'World', emoji: 'âš½', },
{ id: 20585, sportmonksId: 585, name: 'Ettan: North', shortName: 'Ettan: North', country: 'World', emoji: 'âš½', },
{ id: 20588, sportmonksId: 588, name: 'Ettan: South', shortName: 'Ettan: South', country: 'World', emoji: 'âš½', },
{ id: 207, sportmonksId: 591, name: 'Super League', shortName: 'Swiss', country: 'World', countryCode: 'CH', emoji: 'ðŸ‡¨ðŸ‡­', },
{ id: 20594, sportmonksId: 594, name: 'Challenge League', shortName: 'Challenge Leagu', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 203, sportmonksId: 600, name: 'Super Lig', shortName: 'TÃ¼rkiye', country: 'World', countryCode: 'TR', emoji: 'ðŸ‡¹ðŸ‡·', },
{ id: 20603, sportmonksId: 603, name: '1. Lig', shortName: '1. Lig', country: 'World', emoji: 'âš½', },
{ id: 20606, sportmonksId: 606, name: 'Turkish Cup', shortName: 'Turkish Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 333, sportmonksId: 609, name: 'Premier League', shortName: 'Ukraine', country: 'World', countryCode: 'UA', emoji: 'ðŸ‡ºðŸ‡¦', },
{ id: 20624, sportmonksId: 624, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 128, sportmonksId: 636, name: 'Liga Profesional de Fútbol', shortName: 'Argentina', country: 'World', countryCode: 'AR', emoji: 'ðŸ‡¦ðŸ‡·', },
{ id: 20639, sportmonksId: 639, name: 'Torneo Federal B - Pampeana Norte', shortName: 'Torneo Federal ', country: 'World', emoji: 'âš½', },
{ id: 20642, sportmonksId: 642, name: 'Copa Argentina', shortName: 'Copa Argentina', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20645, sportmonksId: 645, name: 'Primera B Nacional', shortName: 'Primera B Nacio', country: 'World', emoji: 'âš½', },
{ id: 71, sportmonksId: 648, name: 'Serie A', shortName: 'Brasil A', country: 'World', countryCode: 'BR', emoji: 'ðŸ‡§ðŸ‡·', },
{ id: 72, sportmonksId: 651, name: 'Serie B', shortName: 'Brasil B', country: 'World', countryCode: 'BR', emoji: 'ðŸ‡§ðŸ‡·', },
{ id: 20654, sportmonksId: 654, name: 'Copa do Brasil', shortName: 'Copa do Brasil', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20657, sportmonksId: 657, name: 'Serie C', shortName: 'Serie C', country: 'World', emoji: 'âš½', },
{ id: 20660, sportmonksId: 660, name: 'Serie D', shortName: 'Serie D', country: 'World', emoji: 'âš½', },
{ id: 20663, sportmonksId: 663, name: 'Primera Division', shortName: 'Primera Divisio', country: 'World', emoji: 'âš½', },
{ id: 20666, sportmonksId: 666, name: 'Primera B', shortName: 'Primera B', country: 'World', emoji: 'âš½', },
{ id: 20672, sportmonksId: 672, name: 'Liga BetPlay', shortName: 'Liga BetPlay', country: 'World', emoji: 'âš½', },
{ id: 20678, sportmonksId: 678, name: 'Primera B', shortName: 'Primera B', country: 'World', emoji: 'âš½', },
{ id: 20687, sportmonksId: 687, name: 'Primera Division', shortName: 'Primera Divisio', country: 'World', emoji: 'âš½', },
{ id: 20696, sportmonksId: 696, name: 'Liga Pro', shortName: 'Liga Pro', country: 'World', emoji: 'âš½', },
{ id: 20711, sportmonksId: 711, name: 'CAF World Cup Qualifiers', shortName: 'CAF World Cup Q', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20714, sportmonksId: 714, name: 'WC Qualification Asia', shortName: 'WC Qualificatio', country: 'World', emoji: 'âš½', },
{ id: 20717, sportmonksId: 717, name: 'WC Qualification Concacaf', shortName: 'WC Qualificatio', country: 'World', emoji: 'âš½', },
{ id: 20720, sportmonksId: 720, name: 'WC Qualification Europe', shortName: 'WC Qualificatio', country: 'World', emoji: 'âš½', },
{ id: 20723, sportmonksId: 723, name: 'WC Qualification Oceania', shortName: 'WC Qualificatio', country: 'World', emoji: 'âš½', },
{ id: 20726, sportmonksId: 726, name: 'WC Qualification South America', shortName: 'WC Qualificatio', country: 'World', emoji: 'âš½', },
{ id: 20729, sportmonksId: 729, name: 'WC Qualification Intercontinental Playoffs', shortName: 'WC Qualificatio', country: 'World', emoji: 'âš½', },
{ id: 20732, sportmonksId: 732, name: 'World Cup', shortName: 'World Cup', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 262, sportmonksId: 743, name: 'Liga MX', shortName: 'Liga MX', country: 'World', countryCode: 'MX', emoji: 'ðŸ‡²ðŸ‡½', },
{ id: 20746, sportmonksId: 746, name: 'Copa MX', shortName: 'Copa MX', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20749, sportmonksId: 749, name: 'Liga de Expansión MX', shortName: 'Liga de Expansi', country: 'World', emoji: 'âš½', },
{ id: 20755, sportmonksId: 755, name: 'Division 1', shortName: 'Division 1', country: 'World', emoji: 'âš½', },
{ id: 20764, sportmonksId: 764, name: 'Primera Division', shortName: 'Primera Divisio', country: 'World', emoji: 'âš½', },
{ id: 20767, sportmonksId: 767, name: 'Segunda Division', shortName: 'Segunda Divisio', country: 'World', emoji: 'âš½', },
{ id: 20770, sportmonksId: 770, name: 'Primera Division', shortName: 'Primera Divisio', country: 'World', emoji: 'âš½', },
{ id: 253, sportmonksId: 779, name: 'Major League Soccer', shortName: 'MLS', country: 'World', countryCode: 'US', emoji: 'ðŸ‡ºðŸ‡¸', },
{ id: 20782, sportmonksId: 782, name: 'US Open Cup', shortName: 'US Open Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20788, sportmonksId: 788, name: 'NASL', shortName: 'NASL', country: 'World', emoji: 'âš½', },
{ id: 20791, sportmonksId: 791, name: 'USL Championship', shortName: 'USL Championshi', country: 'World', emoji: 'âš½', },
{ id: 20800, sportmonksId: 800, name: 'Primera Division', shortName: 'Primera Divisio', country: 'World', emoji: 'âš½', },
{ id: 20806, sportmonksId: 806, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 20809, sportmonksId: 809, name: 'Ligue 1', shortName: 'Ligue 1', country: 'World', emoji: 'âš½', },
{ id: 20827, sportmonksId: 827, name: 'Ligue 1', shortName: 'Ligue 1', country: 'World', emoji: 'âš½', },
{ id: 233, sportmonksId: 830, name: 'Premier League', shortName: 'Egypt', country: 'World', countryCode: 'EG', emoji: 'ðŸ‡ªðŸ‡¬', },
{ id: 20851, sportmonksId: 851, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 20860, sportmonksId: 860, name: 'Botola Pro', shortName: 'Botola Pro', country: 'World', emoji: 'âš½', },
{ id: 20902, sportmonksId: 902, name: 'Persian Gulf Pro League', shortName: 'Persian Gulf Pr', country: 'World', emoji: 'âš½', },
{ id: 20911, sportmonksId: 911, name: 'Iraqi League', shortName: 'Iraqi League', country: 'World', emoji: 'âš½', },
{ id: 20920, sportmonksId: 920, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 20923, sportmonksId: 923, name: 'Zain Premier League', shortName: 'Zain Premier Le', country: 'World', emoji: 'âš½', },
{ id: 20935, sportmonksId: 935, name: 'Professional League', shortName: 'Professional Le', country: 'World', emoji: 'âš½', },
{ id: 20938, sportmonksId: 938, name: 'Stars League', shortName: 'Stars League', country: 'World', emoji: 'âš½', },
{ id: 307, sportmonksId: 944, name: 'Pro League', shortName: 'Saudi Pro', country: 'World', countryCode: 'SA', emoji: 'ðŸ‡¸ðŸ‡¦', },
{ id: 20947, sportmonksId: 947, name: 'Division 1', shortName: 'Division 1', country: 'World', emoji: 'âš½', },
{ id: 20950, sportmonksId: 950, name: 'Kings Cup', shortName: 'Kings Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 20956, sportmonksId: 956, name: 'Ligue 1', shortName: 'Ligue 1', country: 'World', emoji: 'âš½', },
{ id: 20959, sportmonksId: 959, name: 'UAE Pro League', shortName: 'UAE Pro League', country: 'World', emoji: 'âš½', },
{ id: 98, sportmonksId: 968, name: 'J1 League', shortName: 'J1', country: 'World', countryCode: 'JP', emoji: 'ðŸ‡¯ðŸ‡µ', },
{ id: 20971, sportmonksId: 971, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 20983, sportmonksId: 983, name: 'Canadian Soccer League', shortName: 'Canadian Soccer', country: 'World', emoji: 'âš½', },
{ id: 169, sportmonksId: 989, name: 'Super League', shortName: 'China', country: 'World', countryCode: 'CN', emoji: 'ðŸ‡¨ðŸ‡³', },
{ id: 20992, sportmonksId: 992, name: 'League One', shortName: 'League One', country: 'World', emoji: 'âš½', },
{ id: 21007, sportmonksId: 1007, name: 'Indian Super League', shortName: 'Indian Super Le', country: 'World', emoji: 'âš½', },
{ id: 21016, sportmonksId: 1016, name: 'Indonesia Championship', shortName: 'Indonesia Champ', country: 'World', emoji: 'âš½', },
{ id: 21019, sportmonksId: 1019, name: 'Liga 1', shortName: 'Liga 1', country: 'World', emoji: 'âš½', },
{ id: 21022, sportmonksId: 1022, name: 'J2-League', shortName: 'J2-League', country: 'World', emoji: 'âš½', },
{ id: 21025, sportmonksId: 1025, name: 'J3-League', shortName: 'J3-League', country: 'World', emoji: 'âš½', },
{ id: 21028, sportmonksId: 1028, name: 'Emperor Cup', shortName: 'Emperor Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21031, sportmonksId: 1031, name: 'J-League Cup', shortName: 'J-League Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 292, sportmonksId: 1034, name: 'K League 1', shortName: 'K League', country: 'World', countryCode: 'KR', emoji: 'ðŸ‡°ðŸ‡·', },
{ id: 21049, sportmonksId: 1049, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 21064, sportmonksId: 1064, name: 'Thai Premier League', shortName: 'Thai Premier Le', country: 'World', emoji: 'âš½', },
{ id: 21067, sportmonksId: 1067, name: 'Thai League Two', shortName: 'Thai League Two', country: 'World', emoji: 'âš½', },
{ id: 21073, sportmonksId: 1073, name: 'V-League', shortName: 'V-League', country: 'World', emoji: 'âš½', },
{ id: 21082, sportmonksId: 1082, name: 'Friendly International', shortName: 'Friendly Intern', country: 'World', emoji: 'ðŸ¤', },
{ id: 21085, sportmonksId: 1085, name: 'AFC Champions League Elite', shortName: 'AFC Champions L', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21088, sportmonksId: 1088, name: 'AFC Champions League Two', shortName: 'AFC Champions L', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21092, sportmonksId: 1092, name: 'Enterprise National League South', shortName: 'Enterprise Nati', country: 'World', emoji: 'âš½', },
{ id: 21098, sportmonksId: 1098, name: 'Liga De Futbol Prof', shortName: 'Liga De Futbol ', country: 'World', emoji: 'âš½', },
{ id: 667, sportmonksId: 1101, name: 'Club Friendlies 1', shortName: 'Friendlies', country: 'World', emoji: 'ðŸ¤', isCup: true, isInternational: true, },
{ id: 21103, sportmonksId: 1103, name: 'African Nations Championship', shortName: 'African Nations', country: 'World', emoji: 'âš½', },
{ id: 21104, sportmonksId: 1104, name: 'ASEAN Championship', shortName: 'ASEAN Champions', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21105, sportmonksId: 1105, name: 'AFC Asian Cup', shortName: 'AFC Asian Cup', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21106, sportmonksId: 1106, name: 'Asian Cup Qualification', shortName: 'Asian Cup Quali', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21107, sportmonksId: 1107, name: 'CAF Champions League', shortName: 'CAF Champions L', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21108, sportmonksId: 1108, name: 'CAF Confederations Cup', shortName: 'CAF Confederati', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21111, sportmonksId: 1111, name: 'CONCACAF Champions Cup', shortName: 'CONCACAF Champi', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21112, sportmonksId: 1112, name: 'CONCACAF Gold Cup', shortName: 'CONCACAF Gold C', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21114, sportmonksId: 1114, name: 'Copa America', shortName: 'Copa America', country: 'International', emoji: 'ðŸ†', isInternational: true, },
{ id: 11, sportmonksId: 1116, name: 'Copa Sudamericana', shortName: 'Sudamericana', country: 'International', emoji: 'ðŸ†', isInternational: true, },
{ id: 21117, sportmonksId: 1117, name: 'Africa Cup of Nations', shortName: 'Africa Cup of N', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21118, sportmonksId: 1118, name: 'Africa Cup of Nations Qualifications', shortName: 'Africa Cup of N', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21119, sportmonksId: 1119, name: 'EAFF E-1 Football Championship', shortName: 'EAFF E-1 Footba', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 17, sportmonksId: 1122, name: 'Copa Libertadores', shortName: 'Libertadores', country: 'International', emoji: 'ðŸ†', isInternational: true, },
{ id: 21123, sportmonksId: 1123, name: 'OFC Champions League', shortName: 'OFC Champions L', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21124, sportmonksId: 1124, name: 'OFC Nations Cup', shortName: 'OFC Nations Cup', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21125, sportmonksId: 1125, name: 'Olympic Games', shortName: 'Olympic Games', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21126, sportmonksId: 1126, name: 'Olympic Games Women', shortName: 'Olympic Games W', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21127, sportmonksId: 1127, name: 'SAFF Championship', shortName: 'SAFF Championsh', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21128, sportmonksId: 1128, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21176, sportmonksId: 1176, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21202, sportmonksId: 1202, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21203, sportmonksId: 1203, name: 'Serie C: Girone A', shortName: 'Serie C: Girone', country: 'World', emoji: 'âš½', },
{ id: 21204, sportmonksId: 1204, name: 'Serie C: Girone B', shortName: 'Serie C: Girone', country: 'World', emoji: 'âš½', },
{ id: 21205, sportmonksId: 1205, name: 'Serie C: Girone C', shortName: 'Serie C: Girone', country: 'World', emoji: 'âš½', },
{ id: 21224, sportmonksId: 1224, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21251, sportmonksId: 1251, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21291, sportmonksId: 1291, name: 'Baiano 1', shortName: 'Baiano 1', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 21294, sportmonksId: 1294, name: 'Copa do Nordeste', shortName: 'Copa do Nordest', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21296, sportmonksId: 1296, name: 'Carioca Serie A', shortName: 'Carioca Serie A', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 21300, sportmonksId: 1300, name: 'Cearense 1', shortName: 'Cearense 1', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 21302, sportmonksId: 1302, name: 'Gaucho 1', shortName: 'Gaucho 1', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 21307, sportmonksId: 1307, name: 'Mineiro 1', shortName: 'Mineiro 1', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 21311, sportmonksId: 1311, name: 'Paranaense 1', shortName: 'Paranaense 1', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 21313, sportmonksId: 1313, name: 'Paulista A1', shortName: 'Paulista A1', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 21316, sportmonksId: 1316, name: 'Pernambucano 1', shortName: 'Pernambucano 1', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 21325, sportmonksId: 1325, name: 'Euro Qualification', shortName: 'Euro Qualificat', country: 'World', emoji: 'âš½', },
{ id: 21326, sportmonksId: 1326, name: 'European Championship', shortName: 'European Champi', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21327, sportmonksId: 1327, name: 'Euro U21', shortName: 'Euro U21', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 531, sportmonksId: 1328, name: 'UEFA Super Cup', shortName: 'Super Cup', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21329, sportmonksId: 1329, name: 'UEFA Youth League', shortName: 'UEFA Youth Leag', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21355, sportmonksId: 1355, name: 'Euro U19', shortName: 'Euro U19', country: 'World', emoji: 'âš½', },
{ id: 21356, sportmonksId: 1356, name: 'A-League Men', shortName: 'A-League Men', country: 'World', emoji: 'âš½', },
{ id: 21362, sportmonksId: 1362, name: 'K League 2', shortName: 'K League 2', country: 'World', emoji: 'âš½', },
{ id: 21363, sportmonksId: 1363, name: 'Friendly International Women', shortName: 'Friendly Intern', country: 'World', emoji: 'ðŸ¤', },
{ id: 21364, sportmonksId: 1364, name: 'World Cup U20', shortName: 'World Cup U20', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21369, sportmonksId: 1369, name: 'World Cup Women', shortName: 'World Cup Women', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 532, sportmonksId: 1371, name: 'UEFA Europa League Play-offs', shortName: 'UEL P/O', country: 'World', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21379, sportmonksId: 1379, name: 'Cosafa Cup', shortName: 'Cosafa Cup', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21389, sportmonksId: 1389, name: 'UEFA Women\'s EURO', shortName: 'UEFA Women\'s EU', country: 'World', emoji: 'âš½', },
{ id: 21403, sportmonksId: 1403, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21412, sportmonksId: 1412, name: 'Egypt Cup', shortName: 'Egypt Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21419, sportmonksId: 1419, name: 'UEFA Women\'s Champions League', shortName: 'UEFA Women\'s Ch', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21434, sportmonksId: 1434, name: 'Atlantic Cup', shortName: 'Atlantic Cup', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21450, sportmonksId: 1450, name: 'Coppa Italia Serie C', shortName: 'Coppa Italia Se', country: 'World', emoji: 'âš½', isCup: true, },
{ id: 21452, sportmonksId: 1452, name: 'FIFA Intercontinental Cup', shortName: 'FIFA Interconti', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21479, sportmonksId: 1479, name: 'Concacaf League', shortName: 'Concacaf League', country: 'World', emoji: 'âš½', },
{ id: 21502, sportmonksId: 1502, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21538, sportmonksId: 1538, name: 'UEFA Nations League', shortName: 'UEFA Nations Le', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21546, sportmonksId: 1546, name: 'Central American & Caribbean Games', shortName: 'Central America', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21555, sportmonksId: 1555, name: 'Asian Games', shortName: 'Asian Games', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21557, sportmonksId: 1557, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21568, sportmonksId: 1568, name: 'Primera Division Women', shortName: 'Primera Divisio', country: 'World', emoji: 'âš½', },
{ id: 21578, sportmonksId: 1578, name: 'Serie A Women', shortName: 'Serie A Women', country: 'World', emoji: 'âš½', },
{ id: 21583, sportmonksId: 1583, name: 'A-League Women', shortName: 'A-League Women', country: 'World', emoji: 'âš½', },
{ id: 21607, sportmonksId: 1607, name: 'USL League One', shortName: 'USL League One', country: 'World', emoji: 'âš½', },
{ id: 21631, sportmonksId: 1631, name: 'Brasileiro Women', shortName: 'Brasileiro Wome', country: 'World', emoji: 'âš½', },
{ id: 21658, sportmonksId: 1658, name: 'Copa de la Superliga', shortName: 'Copa de la Supe', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21659, sportmonksId: 1659, name: 'Superliga Play-offs', shortName: 'Superliga Play-', country: 'World', emoji: 'âš½', },
{ id: 21673, sportmonksId: 1673, name: 'Ligue 1 Play-offs', shortName: 'Ligue 1 Play-of', country: 'World', emoji: 'âš½', },
{ id: 21681, sportmonksId: 1681, name: 'Super League Play-offs', shortName: 'Super League Pl', country: 'World', emoji: 'âš½', },
{ id: 21682, sportmonksId: 1682, name: 'Parva Liga - Play-offs', shortName: 'Parva Liga - Pl', country: 'World', emoji: 'âš½', },
{ id: 21689, sportmonksId: 1689, name: 'Premier League', shortName: 'Premier League', country: 'World', emoji: 'âš½', },
{ id: 21690, sportmonksId: 1690, name: 'King\'s Cup', shortName: 'King\'s Cup', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 21691, sportmonksId: 1691, name: 'Premier League - Playoffs', shortName: 'Premier League ', country: 'World', emoji: 'âš½', },
{ id: 21714, sportmonksId: 1714, name: 'Pacific Games', shortName: 'Pacific Games', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21729, sportmonksId: 1729, name: 'Southeast Asian Games', shortName: 'Southeast Asian', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21740, sportmonksId: 1740, name: 'Google Pixel Frauen-Bundesliga', shortName: 'Google Pixel Fr', country: 'World', emoji: 'âš½', },
{ id: 21741, sportmonksId: 1741, name: 'CONCACAF Nations League', shortName: 'CONCACAF Nation', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21742, sportmonksId: 1742, name: 'CONCACAF Nations League Qualification', shortName: 'CONCACAF Nation', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21784, sportmonksId: 1784, name: 'CONMEBOL Pre-Olympic Tournament', shortName: 'CONMEBOL Pre-Ol', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 21797, sportmonksId: 1797, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21798, sportmonksId: 1798, name: 'Supercopa do Brasil', shortName: 'Supercopa do Br', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21885, sportmonksId: 1885, name: 'Nwsl Challenge Cup Women', shortName: 'Nwsl Challenge ', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21989, sportmonksId: 1989, name: 'Qatar Prince Cup', shortName: 'Qatar Prince Cu', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 21990, sportmonksId: 1990, name: 'Super Cup', shortName: 'Super Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 22040, sportmonksId: 2040, name: 'Olympic Qualifying Concacaf', shortName: 'Olympic Qualify', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 13, sportmonksId: 2286, name: 'Europa Conference League', shortName: 'UECL', country: 'International', emoji: 'ðŸ†', isInternational: true, },
{ id: 22321, sportmonksId: 2321, name: 'CONCACAF Gold Cup Qualification', shortName: 'CONCACAF Gold C', country: 'International', emoji: 'ðŸ†', isCup: true, isInternational: true, },
{ id: 22328, sportmonksId: 2328, name: 'NWSL', shortName: 'NWSL', country: 'World', emoji: 'âš½', },
{ id: 22450, sportmonksId: 2450, name: 'Club Friendlies 2', shortName: 'Club Friendlies', country: 'World', emoji: 'ðŸ¤', },
{ id: 22451, sportmonksId: 2451, name: 'Club Friendlies 3', shortName: 'Club Friendlies', country: 'World', emoji: 'ðŸ¤', },
{ id: 22452, sportmonksId: 2452, name: 'Club Friendlies 4', shortName: 'Club Friendlies', country: 'World', emoji: 'ðŸ¤', },
{ id: 22528, sportmonksId: 2528, name: 'League Cup', shortName: 'League Cup', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 22545, sportmonksId: 2545, name: 'MLS Next Pro', shortName: 'MLS Next Pro', country: 'World', emoji: 'âš½', },
{ id: 22679, sportmonksId: 2679, name: 'African Nations Championship Qualification', shortName: 'African Nations', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 23232, sportmonksId: 3232, name: 'Olympic Qualifying: Oceania', shortName: 'Olympic Qualify', country: 'World', emoji: 'âš½', },
{ id: 23320, sportmonksId: 3320, name: 'All Africa Games', shortName: 'All Africa Game', country: 'International', emoji: 'âš½', isInternational: true, },
{ id: 23360, sportmonksId: 3360, name: 'Olympics Intercontinental Play-offs', shortName: 'Olympics Interc', country: 'World', emoji: 'âš½', },
{ id: 23412, sportmonksId: 3412, name: 'FIFA Club World Cup', shortName: 'FIFA Club World', country: 'World', emoji: 'ðŸ†', isCup: true, },
{ id: 23431, sportmonksId: 3431, name: 'EAFF Football Championship Qualification', shortName: 'EAFF Football C', country: 'International', emoji: 'âš½', isInternational: true, },
];

export const DEFAULT_LEAGUE_IDS = DEFAULT_LEAGUES.map((l) => l.id);

const LEAGUE_BY_ID = new Map<number, TrackedLeague>(DEFAULT_LEAGUES.map((l) => [l.id, l]));

export const getLeagueById = (id: number): TrackedLeague | undefined => LEAGUE_BY_ID.get(id);

/** API-Football style internal ID -> Sportmonks league ID. */
export const LEAGUE_TO_SPORTMONKS: Record<number, number> = Object.fromEntries(
  DEFAULT_LEAGUES.map((l) => [l.id, l.sportmonksId]),
);

/** Sportmonks league ID -> internal ID. */
export const SPORTMONKS_TO_LEAGUE: Record<number, number> = Object.fromEntries(
  DEFAULT_LEAGUES.map((l) => [l.sportmonksId, l.id]),
);
